# for local testing on mysql
version: '2'
services:
  mysql:
    image: mysql:5.5.42
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql:3306
